### ISSUE TITLE
React 18 support?

### ISSUE THREAD

**Issue by bennlongg** [Rocketmakers/api-hooks#4]
currently, all providers will error as FC doesn't contain children anymore

and the peer deps are tied to 17.0.1

**Comment by bennlongg** [comment]
currently, all providers will error as FC doesn't contain children anymore

and the peer deps are tied to 17.0.1

**Comment by jlews** [comment]
Resolved by https://github.com/Rocketmakers/api-hooks/pull/5

**Comment by jlews** [comment]
Released in version `1.4.0`
